#!/bin/bash

echo "Pulling https://hub.docker/r/assaflavie/runlike"
docker pull --quiet assaflavie/runlike
echo "Running runlike to get run command generated by Unraid dockerMan"
RUN=$(docker run --rm -v/var/run/docker.sock:/var/run/docker.sock assaflavie/runlike PhoenixMiner)
echo "Cleaning up"
docker rmi --force assaflavie/runlike
echo "Modifying command to make it interactive"
RUN=$(echo "$RUN" | sed -e "s/ --detach=true / --interactive --tty /")
docker stop PhoenixMiner
docker rm PhoenixMiner
echo $RUN
